
##sregistry.iblog.pro
server = "https://sregistry.iblog.pro"

[host."https://sregistry.iblog.pro"]
  capabilities = ["pull"]                  # Requires less trust, won't resolve tag to digest from this host


#server = "https://registry-1.docker.io"    # Exclude this to not use upstream
#
#[host."https://public-mirror.example.com"]
#  capabilities = ["pull"]                  # Requires less trust, won't resolve tag to digest from this host
